---
apiVersion: v1
kind: Namespace
metadata:
  name: psk-system
  labels:
    app.kubernetes.io/managed-by: psk-aws-control-plane-base
    platform-vault: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    app.kubernetes.io/managed-by: psk-aws-control-plane-base